# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/data/data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf.common import messageData_pb2 as protobuf_dot_common_dot_messageData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/data/data.proto',
  package='protobuf.data',
  syntax='proto3',
  serialized_pb=_b('\n\x18protobuf/data/data.proto\x12\rprotobuf.data\x1a!protobuf/common/messageData.proto\"{\n\x03Msg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\x12\x10\n\x08\x66ile_ext\x18\x03 \x01(\t\x12\r\n\x05\x66rame\x18\x04 \x01(\x03\x12\x33\n\r_message_data\x18\x05 \x01(\x0b\x32\x1c.protobuf.common.messageDatab\x06proto3')
  ,
  dependencies=[protobuf_dot_common_dot_messageData__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='protobuf.data.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='protobuf.data.Msg.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_name', full_name='protobuf.data.Msg.app_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_ext', full_name='protobuf.data.Msg.file_ext', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame', full_name='protobuf.data.Msg.frame', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_message_data', full_name='protobuf.data.Msg._message_data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=201,
)

_MSG.fields_by_name['_message_data'].message_type = protobuf_dot_common_dot_messageData__pb2._MESSAGEDATA
DESCRIPTOR.message_types_by_name['Msg'] = _MSG

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'protobuf.data.data_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.data.Msg)
  ))
_sym_db.RegisterMessage(Msg)


# @@protoc_insertion_point(module_scope)
